### ISSUE TITLE
ProtoBuf is faster for some datasets

### ISSUE THREAD

**Issue by charris123** [tomba/netserializer#25]
I sent tomba my actual code.
Below are my results.  For me, deserialization is the most important.
Serializer.Initialize() in 70 ms == 100000
NetSerializer | MemStream Serialize   |       2064 |   8   2   2 |  128300000 |
NetSerializer | MemStream Deserialize |       4140 | 101  35   1 |            |
protobuf-net  | MemStream Serialize   |       1897 |  56   1   0 |  129097100 |
protobuf-net  | MemStream Deserialize |       3542 |  80  27   0 |            |

These are tests with my actual dataset
I can also see better performance with Protobuf with the following modifications to the example.  The differences are smaller, but Protobuf is still faster

[Serializable]
	[ProtoContract]
	sealed class U8Message : MessageBase
	{	

		[ProtoMember(1)]
		public decimal Price { get; set; }

		[ProtoMember(2)]
		public int Volume { get; set; }

		[ProtoMember(3)]
		public int CompanyId { get; set; }

		[ProtoMember(5)]
		public int MinQty { get; set; }

		[ProtoMember(6)]
		public string CorrelationClOrdID { get; set; }

		public U8Message()
		{
		}

		public U8Message(MyRandom r)
		{
			Price = r.Next();
			Volume = (int)r.Next();
			CompanyId = (int)r.Next();
			MinQty = (int)r.Next();
			CorrelationClOrdID = new Guid().ToString();

		}

		public static U8Message Create(MyRandom r)
		{
			return new U8Message(r);
		}

		public override void Compare(MessageBase msg)
		{
			var m = (U8Message)msg;
			A(Price == m.Price);
			A(Volume == m.Volume);
			A(CompanyId == m.CompanyId);
			A(MinQty == m.MinQty);
			A(CorrelationClOrdID == m.CorrelationClOrdID);
		}
	}

**Comment by tomba** [comment]
I pushed improvements to Decimal and Nullable<> handling into the master branch. You may want to try with those patches.

I also noticed that protobuf serializes DateTime faster than NetSerializer.

**Comment by charris123** [comment]
Thank you for the quick patch.  Definitely an improvement.  Times for my full dataset are now very close.  Protobuf is still slightly faster, but only by a small percent.

I think you are correct about the DateTime.  If I remove the DateTime from my classes, then NetSerializer is 10-15% faster for the rest of my data.

**Comment by tomba** [comment]
Ok. I'll close this one, and create a new issue for DateTime improvement to have a more specific description for the issue.
