### ISSUE TITLE
VersionSerializer

### ISSUE THREAD

**Issue by jogibear9988** [tomba/netserializer#30]
Here's a Serializer for .NET Version Type...

**Comment by jogibear9988** [comment]
class VersionSerializer : IStaticTypeSerializer
    {
        public bool Handles(Type type)
        {
            return type == typeof(Version);
        }

        public IEnumerable<Type> GetSubtypes(Type type)
        {
            yield break;
        }

        public MethodInfo GetStaticWriter(Type type)
        {
            return typeof(VersionSerializer).GetMethod(
                "WritePrimitive",
                BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.ExactBinding,
                null,
                new Type[] { typeof(Stream), type },
                null);
        }

        public MethodInfo GetStaticReader(Type type)
        {
            return typeof(VersionSerializer).GetMethod("ReadPrimitive",
                BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.ExactBinding, null,
                new Type[] { typeof(Stream), type.MakeByRefType() }, null);
        }

        static void WritePrimitive(Stream stream, Version value)
        {
            if (value == null)
            {
                Primitives.WritePrimitive(stream, (uint) 0);
                return;
            }

            Primitives.WritePrimitive(stream, value.Major);
            Primitives.WritePrimitive(stream, value.Minor);
            Primitives.WritePrimitive(stream, value.Revision);
            Primitives.WritePrimitive(stream, value.Build);
        }

        static void ReadPrimitive(Stream stream, out Version value)
        {
            int l1, l2, l3, l4, l5;

            Primitives.ReadPrimitive(stream, out l1);

            if (l1 == 0)
            {
                value = null;
                return;
            }
 
            Primitives.ReadPrimitive(stream, out l2);
            Primitives.ReadPrimitive(stream, out l3);
            Primitives.ReadPrimitive(stream, out l4);
            Primitives.ReadPrimitive(stream, out l5);
            value = new Version(l2, l3, l4, l5);     
        }
    }

**Comment by tomba** [comment]
Please send a pull request if you want code to be merged.
