### ISSUE TITLE
Support for Mono on other Endianess

### ISSUE THREAD

**Issue by jogibear9988** [tomba/netserializer#32]
I try to use to communicate with a Service wich run's on Mono on a Architecture with a different endianness! Then I got a Exception that it tries to read over the end of the stream.

**Comment by jogibear9988** [comment]
The class consits of a Guid, a Enum, a string and a Interface wich is implemented by a Subclass (wich is a empty class)

**Comment by tomba** [comment]
NetSerializer is designed only for little endian platforms.

That said, it might not be a too difficult task to make it endian-independent. The problems are probably in Primitives.cs.

**Comment by jogibear9988** [comment]
i know!
hopfully i'm able to implement it

**Comment by jogibear9988** [comment]
I thought it was a Endianess Problem, but the other archtiecture is also little endian, so thats not the problem! Have you tried netserializer on mono??

**Comment by tomba** [comment]
Yes, but not the most recent version.

**Comment by jogibear9988** [comment]
my problem is, it works on windows, on mono i got a exception that we read beyond the end of the stream... i will find out whats wrong

**Comment by tomba** [comment]
Did you try the test suite? It works fine for me on Linux and mono 3.2.8. Although I had to make a few trivial changes to get NetSerializer compile on 4.5, but those should not have any effect.

**Comment by jogibear9988** [comment]
I've found the problem! When I use the following Code: 
              _serializer = new Serializer(typeof(AbstractWebRequest).Assembly.GetTypes().OrderBy(x => x.Namespace).ThenBy(x => x.Name), 
                new ITypeSerializer[] { new VersionSerializer(), new MyGenericSerializer(), }); 

the type: IntialWebRequest hast the Id 259 on mono and 261 on MS.Net! I will find out what is the difference

**Comment by tomba** [comment]
If you use code like that you need to be sure that the assembly containing AbstractWebRequest is the same on client and the server. If, say, the assembly on the server contains just one extra class, the serialization will be broken.

I guess it's also possible that the compiler may add extra classes to an assembly, for example when generating helper classes for 'yield'.

**Comment by jogibear9988** [comment]
Is fixed by #38
