### ISSUE TITLE
compile error?

### ISSUE THREAD

**Issue by ricardok1** [tomba/netserializer#40]
Hi there

There's any trick to compile?
Error:
'NetSerializer.TypeData.Type.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.
on NetSerializer\TypeData.cs

Thanks
Ricardo

**Comment by tomba** [comment]
NetSerializer requires c# 6.0. I'll change it to work with earlier c# versions.

**Comment by tomba** [comment]
Fixed in 0f26838d62eb1a38e9e9c48b43caa3c163e1a2fa
