### ISSUE TITLE
StackOverFlowException

### ISSUE THREAD

**Issue by jetinotjedi** [tomba/netserializer#41]
Hi!

I was trying to use your serializer with my application.

I have something like:

class Area{...}
class Player{ ... Unit[] Units,  IEnumerable < Area > Areas {get: Units.Select(unit.UnitArea).Distinct() ....}
class Unit{...Area UnitArea, House UnitHouse ...}
class Game {...Area[] AllAreas, House[] AllHouses...}

This is just so you can see the relations. What I was trying to do, is serializing the Game object, thats when i ran into the stackoverflow. In my guess it happens due that the Unit has a reference of its house, so you try to serialize the house, which has units, so you try to serialize the units, etc It is looped.

When I use the BinaryFormatter this issue is not present.

Thank you very much, I hope I can help you.

**Comment by tomba** [comment]
Hi,

NetSerializer doesn't support cyclic references, so you cannot serialize that kind of data. Everything is serialized as plain values.
