### ISSUE TITLE
Support readonly properties

### ISSUE THREAD

**Issue by naster01** [tomba/netserializer#42]
Virtual methods could solve the issue or it could be handled by default in the API.
It is a real need.

	public class Book    
	{        
		private readonly string _Title;
	
		public Book(string title)        
		{            
			_Title = title;        
		}
	
		public string Title => _Title; 
	}

**Comment by tomba** [comment]
Sorry, I don't understand your point. Readonly properties and fields are supported. Please provide an example case that fails if you are seeing problems.
