### ISSUE TITLE
Question about version compatibility

### ISSUE THREAD

**Issue by SurajGupta** [tomba/netserializer#45]
Hello - I have a question about the following from the readme:

"...the sender and the receiver have to have the same versions of the types being serialized...a version upgrade could make the data non-deserializable"

I'm trying to understand what you mean by "version."  Do you mean in it a code-sense (the types have changed in code) or do you mean it in the build/binary-sense (different builds of the assembly containing the serialized types).  For example, if a reader and writer have different builds of the binaries that contain the serialized types, but nothing in code has changed about those types, then is a roundtrip serialization/deserialization safe?  Or is it unsafe because of non-deterministic build steps like optimization (I'm actually not sure if optimization is non-deterministic).

**Comment by tomba** [comment]
Hi,

I mean in the code-sense. If there's a member field added, removed, or the field's type is changed, the serialization will break.

**Comment by SurajGupta** [comment]
much appreciated
