### ISSUE TITLE
Direct Serialization/Deserialization

### ISSUE THREAD

**Issue by SurajGupta** [tomba/netserializer#47]
I can't seem to figure out from the README what the difference is between the direct and not-direct versions of Serialize and Deserialize.  When would you use the "direct" version.  What are the limitations?  It seems to be faster than the non-direct versions.

**Comment by tomba** [comment]
If you do `Serialize(stream, ob)` the serializer will first write the type information about ob to the stream, followed by ob's data. If you do `SerializeDirect(stream, ob)` only ob's data is written, and if ob is a struct, no boxing happens.

With SerializeDirect the deserializing end needs to know what the exact type is, as there's no type information in the stream.

As to when you would use it... I don't have a good example. Maybe if you only ever serialize a single type (which is never inherited, or a struct).

**Comment by SurajGupta** [comment]
makes sense now!  thanks.
