### ISSUE TITLE
Feature Request: add one serializer to another

### ISSUE THREAD

**Issue by SurajGupta** [tomba/netserializer#48]
There doesn't seem to be a way to build a serializer from another serializer, unless you call AddTypes on the first and save the resulting `Dictionary<Type,uint>`.  If one serializer's types are specified via the constructor, then there doesn't seem to be a way to "get" them to add to another serializer.  What would be great is a method or a constructor overload (or both!) that adds one serializer to another.

for example:

`void AddTypes(Serializer otherSerializer)`

**Comment by tomba** [comment]
True. But what are you doing with two identical serializer instances? Why is one not enough? =)

**Comment by SurajGupta** [comment]
Lets say you have two projects (in separate VS solutions) with types you want to serialize.  The first project, ProjectA, has a dependency on ProjectB.  ProjectA has a `CreateSerializer()` method that creates a serializer with some types in ProjectA.  Lets say ProjectB needs to serialize types in both projects.  ProjectB has to duplicate code from ProjectA.  Ideally, ProjectB could do something like this:

    var serializer =  new Serializer(GetMyTypes());
    serializer.AddTypes(ProjectA.CreateSerializer());
    return serializer;

When ProjectC comes along, which also depends on ProjectA, it too can benefit from the centralized serializer creation method.

This is not a fictitious example.  I'm faced with this use-case right now and there's no good way to adhere to DRY.

**Comment by tomba** [comment]
Ok, I see.

Yes, that shouldn't be too difficult. Although it would be good if the generated code would be shared between all instances, but that's a bit more complex. Well, that's an additional optimization.

**Comment by tomba** [comment]
I pushed some commits to "work" branch, can you check it out? It may do what you're looking for.

However, there's no direct clone support, or a constructor that takes another serializer. The problem there is the user's custom serializers. They should be cloned too, but there's no way to do that at the moment.

**Comment by SurajGupta** [comment]
Fantastic!  I like the additional constructor and ability to access the type dictionary.  Thanks!

**Comment by tomba** [comment]
Let's not close it until the feature is in the master branch =)

Did you test it?

**Comment by SurajGupta** [comment]
=)  No, I haven't tested, just reviewed the code.  Is the build published to nuget as a pre-release package?  If not I can just build manually.

**Comment by tomba** [comment]
No, it's not published anywhere else than in my "work" branch.

**Comment by tomba** [comment]
Did you get a chance to test this? I don't have a proper use case for this, so it would be good to hear if it works in some real use case.

**Comment by SurajGupta** [comment]
I'm terribly sorry but I haven't had time to test this yet - can we leave it open for a month or so?  My wife and I have a newborn baby so things have been kindda crazy =)

**Comment by tomba** [comment]
I think this is implemented in 4.1. Reopen if it doesn't fulfill the requirement.
