### ISSUE TITLE
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in NetSerializer.dll

### ISSUE THREAD

**Issue by cwhankey** [tomba/netserializer#50]
Any tips on debugging this error? 

	NetSerializer.dll!NetSerializer.TypeIDList.this[uint].get(uint idx) Line 41	C#
 	NetSerializer.dll!NetSerializer.Serializer.GetDeserializeTrampolineFromId(uint id) Line 241	C#
 	NetSerializer.dll!NetSerializer.ObjectSerializer.Deserialize(NetSerializer.Serializer serializer, System.IO.Stream stream, out object ob) Line 79	C#
 	NetSerializer.dll!NetSerializer.Serializer.Deserialize(System.IO.Stream stream) Line 187	C#
 	ConsoleApplication1.exe!ConsoleApplication1.Program.Main(string[] args) Line 38	C#

**Comment by tomba** [comment]
Probably your serializer and deserializer sides are not in sync. The error is caused by the deserializer reading a TypeID from the stream, and there's no Type registered with that ID on the deserializer side.
