### ISSUE TITLE
How to register types dynamically?

### ISSUE THREAD

**Issue by jayakrishnabh** [tomba/netserializer#51]
Registering the types using the NetSerialization.RegisterType in NetSerialization. 

Have a use case where in types needed to be registered dynamically.
When trying to register the types from second time on wards, getting the following exception **'NetSerializer already initialized'**

How can we register types dynamically (calling NetSerialization.RegisterType) more than once. Is there any possibility to achieve this?

**Comment by tomba** [comment]
There is no NetSerialization.RegisterType method...

**Comment by jayakrishnabh** [comment]
Hey sorry Tom, was referring to older version (1.0.0.0) assembly.
Its working fine with the latest version. Thank you.

**Comment by tomba** [comment]
There was no RegisterType() in v1 either.

**Comment by jayakrishnabh** [comment]
Yeah, its supposed to be mentioned as NetSerializer.Serializer.Initialize() method. Mentioned client wrapper method by mistake.

**Comment by tomba** [comment]
I see. Ok. So the latest version is working fine?

Note also that there's a "work" branch in the git repository which contains new commits that may be of use when adding types dynamically.

**Comment by jayakrishnabh** [comment]
Hi Tom, yes it works with the latest version.

But we have are not able to add a user defined class type that implements ISerializable. How can this be achieved?

**Comment by tomba** [comment]
Sorry for taking so long to reply. Can you explain a bit more what the problem is, perhaps with an example? Note that ISerializable is not supported by the NetSerializer.
