### ISSUE TITLE
Serializer doesn't add primitive types by default anymore

### ISSUE THREAD

**Issue by visubesy** [tomba/netserializer#59]
Before the commit e182708d4aee0622ace45c4162a3eddeebdf7278, Serializer.GenerateTypeData(IEnumerable<Type> rootTypes, ITypeSerializer[] userTypeSerializers) added all types from PrimitivesSerializer. Since that commit, this hasn't been the case anymore.

I am not sure if this change was intended or not. If this change was intended, simply close this issue.

It is no problem to add the primitive types by myself in my application. I just stumbled on this because the behaviour of NetSerializer changed when I upgraded it from 2.0 to 4.1.

The following test fails with NetSerializer 4.1 but it didn't fail with NetSerializer 2.0:

```c#
[TestMethod]
public void Serialize_BoxedInteger()
{
	Type[] types = new Type[] { typeof(object) };
	Serializer serializer = new Serializer(types);

	object nullObject = 5;

	MemoryStream stream = new MemoryStream();
	serializer.Serialize(stream, nullObject);
	stream.Position = 0;
	object deserialized = serializer.Deserialize(stream);
	Assert.AreEqual(nullObject, deserialized, "Unexpected deserialized value.");
}
```

**Comment by tomba** [comment]
The expectation is that the caller will give NetSerializer all the types that NetSerializer must be able to deserialize. Your test assumes NetSerializer knows about int, so it's a wrong assumption.

That said, I don't have a problem with adding the primitive types automatically as known types if more people ask for it. But I rather keep it the way it is now: e.g. how often do you use ulong, or ushort? Adding entry for primitives that are never used by the user is not that much overhead, but overhead still.

So for now, I'll close this.

**Comment by visubesy** [comment]
OK. It is no problem for me to add the primitive types by myself (incidentally my application needs all of them) since I know about the changed behaviour.
