### ISSUE TITLE
Can't deserialize object

### ISSUE THREAD

**Issue by matteke-games** [tomba/netserializer#60]
Hi,
So I have my client server application, but when the server tries to deserialize the message from the client it gives an exception without deserializing the packet.

This is how the server calls the deserialization: IPacket packet = (IPacket)_parentServer.Serializer.Deserialize(deserialized);

_parentServer.Serializer being an instance of the Serializer.cs

The error happens on line 278 in Serializer.cs which narrows down to line 340 in the same file, the ReaderTrampolineDelegate remains null and it cant deserialize the object, using the debugger shows that it does know the class type(ClientDoLogin) but ReaderTrampolineDelegate is just null.
I couldnt really find an answer on google so thats why im asking it here.

Thanks

**Comment by tomba** [comment]
Sorry, I can't say much based on the info above.

What exception you get and where is it thrown?

It's fine if ReaderTrampolineDelegate is null. It will be generated in that case.

My guess is that you haven't initialized NetSerializer with all the types to be serialized, or initialized it differently in the client and server sides.

**Comment by matteke-games** [comment]
Sorry for not giving that much info, while I reran the application to get what you requested, it worked....
After 100 fails it works...
I really dont get it, it never works unless someone asks me for more info, then it works without a problem....
Sorry if I wasted your time, it works flawlessly now
