### ISSUE TITLE
[Serializable] Attribute

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [tomba/netserializer#61]
Hey,
I found this library and its really awesome, a great help.

But I was wondering why is there an artificial limitation to need [Serializable] on the types?
I downloaded the code and removed the checks and everything works just fine.

Maybe that should be an option instead? Sometimes you can't or don't want to modify a type.

**Comment by tomba** [comment]
NetSerializer uses .Net's (old) way of marking classes that can be serialized. If a class hasn't been designed to be serialized, you shouldn't serialize it.
