### ISSUE TITLE
Cant deserialize object

### ISSUE THREAD

**Issue by matteke-games** [tomba/netserializer#63]
Hi,
So the error I first described came back but then with another packet(yay).
So I have my server and client, they use DiffieHellman for encrypted communications, they send each other the handshake, but when the client sent his handshake containing his key. The Deserializer throws a nullreference exception and the server force closes the connection. While the server is deserializing the TypeData returned in TypeIDList.cs line 41 is the id 41. Then in Serializer.cs the function on line 338, I edited it so it looks like this:
internal DeserializeDelegate<object> GetDeserializeTrampolineFromId(uint id)
		{
			var data = m_runtimeTypeIDList[id]; //<-- this just returned null, so it cant generate the trampolinedata?
            try
            {
                if (data.ReaderTrampolineDelegate != null) //<-- this throws a nullreference exception
                    return data.ReaderTrampolineDelegate;
            }
            catch (NullReferenceException)
            {
                lock (m_modifyLock)
                {
                    return GenerateReaderTrampoline(data.Type); //<-- this throws one too, because the data variable is null
                }
            }
            return data.ReaderTrampolineDelegate; // suck a cock //<-- I got a bit mad hihi
        }

Note: I'm gonna leave it in breakpoint mode, just in case you need more info
Regards

**Comment by matteke-games** [comment]
When running it again the parameter of type uint in TypeIDList.cs line 41. idx. does not have 41 anymore but over the 1 million: 1832495

**Comment by tomba** [comment]
Sounds to me that the datastream you give to netserializer is corrupted. Or possibly the way you initialize netserializer's typedata is broken. m_runtimeTypeIDList contains an entry for all known TypeIDs, so if you're getting null or array-out-of-bounds, it's either not been set up correctly or you have an invalid TypeID.

**Comment by matteke-games** [comment]
Hmm, I create a new NetSerializer with PacketRegistry.GetPacketTypes, which in code looks like:
public static Type[] GetPacketTypes()
        {
            return new Type[]
            {
                typeof(ClientDoLogin),
                typeof(ClientCheckUpdate),
                typeof(ClientDiffieHellmanHandshake),
                typeof(ServerClientDoLoginResponse),
                typeof(ServerCheckUpdateResponse),
                typeof(ServerDiffieHellmanHandshake)
            };
        }

Corrupt datastream is possible, going to check that. Thanks

**Comment by matteke-games** [comment]
He....He.....He...... about the data corruption, my protocol uses encryption, as you have seen in my types, it uses DiffieHellman keyexchange. The client receives the public exponent from the server and calculates its own and then the shared random. The client queues the packet that contains its public exponent. But I called the Encrypted = true; right after it, so the packet the server needs to generate the shared random is already encrypted using that random, so indeed in the eyes of the serializer the packet is corrupt hihi, stupid me. Well thanks again for helping :) and its a lovely serializer you made ;)

**Comment by matteke-games** [comment]
Screamed victory too early, in ObjectSerializer.cs on line 80 this call: "var del = serializer.GetDeserializeTrampolineFromId(id);" gives the variable del a value of null, causing another NullReferenceException when running: "del(serializer, stream, out ob);"

**Comment by matteke-games** [comment]
The ID it uses is 11, in breakpoint state I went trough the variables and type ID 11 is the packet that should arrive, so it knows the id, it is the correct packet, but then still when it tries to get the DeserializeTrampolineFromId it throws a nullreferenceexception
