### ISSUE TITLE
NetSerializer java

### ISSUE THREAD

**Issue by matteke-games** [tomba/netserializer#68]
Hi,
I was wondering if java has a similar serializer to allow serialization between a C# and java application?
I kinda tried to implement it myself but I'm a bit new to java. Or if someone could help me with porting to java. The problem is that when deserializing in java the result is 1 while in c# its 118(the id)

Thanks

**Comment by tomba** [comment]
I'm sure it won't be easy. Netserializer doesn't even try to create stable serialization data.
