### ISSUE TITLE
Serialize objects without annotating them with [Serializable]

### ISSUE THREAD

**Issue by Netzeband** [tomba/netserializer#75]
Hello

Is there a way to serialize objects of classes with this library, which are not annotated with `[Serializable]`?

For example this class:
```c#
interface IMessage {}

public class MessageA : IMessage
{
    public string Text { get; set; }
    public int    Value { get; set; }
}
```

Thanks in advance for the answer.

**Comment by tomba** [comment]
You can create custom serializers. See e.g. https://github.com/tomba/netserializer/blob/master/Test/CustomSerializers.cs

**Comment by Netzeband** [comment]
Hello, thanks for that hint.
