### ISSUE TITLE
NetSerializer for REDIS 

### ISSUE THREAD

**Issue by nikossaperas** [tomba/netserializer#78]
Not an issue, just some information.
Concerning the statement: "I think the best (and perhaps only) use for NetSerializer is for sending data over network" - I used NetSerializer for storing objects to REDIS. It seems prety good. 
I made a test with a small object to see the size of the value stored and it is less than the size of the value produced with  MessagePack. So I think it's great not only for sending data over the network but also for storing data - in my case REDIS.

I am not able to find any extensive comparison between the two libraries but seems a really legit package.
Any comment on the above will be really appreciated.

**Comment by tomba** [comment]
The problem with storing data is that you cannot restore the data if any of the types change even a bit. There is no versioning information stored. That is why I don't think storing data with NetSerializer is a good idea.
