### ISSUE TITLE
Most of simple types are not supported

### ISSUE THREAD

**Issue by ElDuderinoBerlin** [tomba/netserializer#79]
UIntPtr<32,64> i.e.

I used:
     **var types = typeof(Type).Assembly.GetTypes() .Where(x => x.IsPrimitive || x == typeof(object) || x == typeof(string) || x == 
         typeof(Type)).ToList();
  _serializer = new Serializer(types);**

but this won't work, sadly.

**Comment by tomba** [comment]
What do you mean "most of simple types"? Are there other than (U)IntPtr?

**Comment by tomba** [comment]
Afaics only the intptr types are not supported. And serializing intptrs is not a good idea. So, I don't see any issue here. Please re-open if you see a problem here.
